!!python/object:argparse.Namespace
batch_size: 16
cond_disc: false
data_path:
- cqtdatasets
- dds
downsamp_factor: 4
epochs: 3000
lambda_feat: 10
load_path: damndds/baseline
log_interval: 100
n_layers_D: 4
n_mel_channels: 84
n_residual_layers: 3
n_test_samples: 8
ndf: 16
ngf: 32
num_D: 3
save_interval: 1000
save_path: damndds/baseline
seq_len: 8192
